### ISSUE TITLE
Missing ann-benchmarks documentation?

### ISSUE THREAD

**Issue by loisaidasam** [spotify/voyager#32]
The README says:

> like [Annoy](https://github.com/spotify/annoy), but with [much higher recall](http://ann-benchmarks.com/)

https://github.com/spotify/voyager/blob/c6d09ccc91d4689b15e99b6df965f4580af85358/README.md#L17

but I don't see any references to Voyager on the ann benchmarks page. Am I missing something?

**Comment by loretoparisi** [comment]
I think they were mentioning the fact that in respect to Annoy, Voyager is using hnsw lib as ANN, hence the base benchmark shows that Voyager has a higher Recall / Queries per seconds than Annoy. You can clearly see this from here.

![image](https://github.com/spotify/voyager/assets/163333/29220ee2-d3ba-4447-a4e3-1ff4e2eac319)

**Comment by loisaidasam** [comment]
Which "base benchmark" are you referring to?

Perhaps faiss's hnsw implementation? or perhaps hnswlib? Those don't seem like fair comparisons, since Voyager is an entirely separate implementation.

Also, I think "clearly" is being generous. The way that the README links to ann-benchmarks suggests that one would see "Voyager" on these charts.

**Comment by ijanderso** [comment]
Closing as it has been added to `ann-benchmarks`: https://github.com/erikbern/ann-benchmarks/pull/473
