### ISSUE TITLE
Fewer than expected results were retrieved during querying the index

### ISSUE THREAD

**Issue by sametdumankaya** [spotify/voyager#38]
Hi,

I'm trying to use `voyager` library instead of `annoy` but encountered with the following problem. Even though there are 25130 elements (see the `num_elements` attribute of the index below) in the Voyager Index, I'm unable to query since it can't find all of the indexes somehow.

<img width="1104" alt="image" src="https://github.com/spotify/voyager/assets/12208827/5c3c37a1-9e17-47c5-8f96-d7bbb7a3765f">

**Comment by markkohdev** [comment]
@sametdumankaya sorry about the delayed response here!  Can you provide some more information on your use case?  Are you attempting to query for N neighbors where N is the number of elements in the index?

**Comment by sametdumankaya** [comment]
> @sametdumankaya sorry about the delayed response here! Can you provide some more information on your use case? Are you attempting to query for N neighbors where N is the number of elements in the index?
> 
> Also can you check to ensure that there are no NaN's in your item set?

Hey again,

There's basically 25310 elements in the set and I'm trying to get similarity scores for all of them using a random embedding. I confirm that there's no NaN's in the item set. Somehow, 4 of the items were not included in the index and there are 25306 items in the index instead of 25310.

**Comment by stephen29xie** [comment]
Hello. This is a recall issue that technically isn't a bug. It can happen during probabilistic construction of a Voyager index depending on the characteristics of the data. You can increase the `M` value to increase recall. See https://github.com/spotify/voyager/pull/88 for more details.

Please feel free to reopen if this problem persists.
