### ISSUE TITLE
do you have paper about algorithms you use ? 

### ISSUE THREAD

**Issue by Sandy4321** [spotify/voyager#67]
what is different from
hnswlib

do you have paper about algorithms you use ?

**Comment by markkohdev** [comment]
Hi @Sandy4321 -- Voyager is built off of the [HNSW algorithm](https://arxiv.org/abs/1603.09320).  Thank you for highlighting that we don't actually link to this paper in the documentation.  I'll go ahead and add that :)

**Comment by Sandy4321** [comment]
great thanks
may I ask
these paper authors
Yury A. Malkov 
and
Dmitry A. Yashunin


took apert in developing  spotify/voyager?

**Comment by markkohdev** [comment]
The authors of that paper have not been involved in the development of the Voyager library, but they were authors of [nmslib](https://github.com/nmslib/nmslib) and [hnswlib](https://github.com/nmslib/hnswlib) which this library was derived from

**Comment by xpurwar** [comment]
Hi,
I was wondering if you needed any help with the documentation and if I could help with that!

**Comment by dylanrb123** [comment]
Closing this issue as the original question has been answered
