### ISSUE TITLE
How to delete vectors from the Voyager Index? What's the best strategy? 

### ISSUE THREAD

**Issue by Lorenzoncina** [spotify/voyager#96]

**Comment by stephen29xie** [comment]
The `Index` class has a `markDeleted`/`mark_deleted` method to _soft_ delete an element from the index.

https://spotify.github.io/voyager/python/reference.html#voyager.Index.mark_deleted
https://spotify.github.io/voyager/java/com/spotify/voyager/jni/Index.html#markDeleted(long)
